hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - process: process1
  - model: model1
  - _self_

data_train:
  raw_train: ../data/raw/train
  processed_train: ../data/processed/train/
  final_train: ../data/final/train/